language: node_js
node_js:
- '12'
before_script:
- npm run lint
script:
- npm run test:ci
deploy:
  provider: heroku
  api_key:
    secure: M3XEyTrot+i1ZVf0W/O4sVqyoYO6XgUDdX0oT9OrOipEzGEb6JzjK8XzJkzT95tfEO4FyVVk5ym/cF/JnXBkGaNx08NnHQgsTFwgk84ReEzQR+wGrdj6bUJo4dR6hdMkgXq+wss0wc7ItvZJ/94BOJAWoLtapze/iYdWqbf0cbWKDI8yZvsSPnYlfgm/0yqUAcC1GcenHrJBZy/n6aeYw57jzr5MNA6JkxixwG7T6ISBlf9vKh5zLnnQpqoj0FLXEVzu93r58lh6vWLq7Xlk3mTI6AHooadArexGLtVBPW+bhSE+ePKe+DU+krsrnb198dP623f0O3Xg9nsfPySi5mTX4CPQLLaF/YIpdZkshGfw/i2uRvVqf6KccgpMeKVmErz7F/sirngTMuM38xB7Ib9WPV1Jfg+LuBMaXy4FQs7B0A1O3vGDYf6Yb0TYF+VyHnoXU5mOftoUfT7lMufHgv10oQJ6X3SfQ/qftFcx44HhYfGqwtpdLJRStSHdMa5r8qzosHxjk1MESrmurVCoCCmfEOVSY7KoFWX999FTIu/gDRJHJ+ikXtXTDUjVQ6gsEgMhUjhfdeV1qJtIn42IESOWgk7rRmAiji7sQoFDWQFXDf7nTlmflZBBq3+oUQmHxfjFCD7U81hj+YLZqsjBhq0xBSgL5YgosVAbKn1uATA=
  app: comments-microservice
  on:
    branch: develop
env:
  global:
    DB_URL:
      secure: NBqMHvR06vXe3fgfEAE4fH3801wRVPpUW6A+DOXtzRSabax2doUhRwgiRjoNJC9EJVrn+F49aRpn+8hVSHQfteBte1ZtEWd4ig10C1WBiv1B+S6Y6px5+TyrZg3vgMP/2BeGcXcUpCc4W5556wzL7FlED7a+TLmcmw2vc875g/69aWlBLIx0ghQBHaWZ3OAfBQSTLlJQV+EMu6dwbOxkivgWaYt9gspZclHpv6oLuF50WJpMiHjLPpkW6vI2DQfaHBIpTKXdvcNvO1hfylZjQGccFYcsRSSXpjvKFyW/K2VBdcOrIQZ81esh5P8zSvADTmV/Qghdv4nyFHHkUWONY/DjTrw9T4LD/wCzeJtb+M+NFeC42LGT0T46V7HtwVVvXPO7f4nCY5VA7bZ14l6O90Y8dCMkpRJY6FDYihg4QxJ0AGn/zLjvozyEj/DzzhretrE2BcTeZf6jf6SpbbUVM3Rd5hqFyP6aSgDsKrQoOHBQVZKQIHYh0BD+q4T62bgQvWT7L/c3H75XMZ7u1S2gwhkSVhtw3g8MowcZGa1NSeXriKy2M5oYgJ+GVTbBc4k+vHrJPwX9HVHNUM7LZoV6quhnsgOT/AW+kKbExO20B0Ml/W/EtwSgDDAG5vFIeJ4Dzyn6I+0RnAEh7/izCFTJgVTQYBZigg5vsbXAN7zRbVo=
